version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: burak123!
      POSTGRES_DB: bitask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
