name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Maven ile projeyi build edin
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

      # Maven ile testleri çalıştırın
      - name: Run tests with Maven
        run: mvn test

      # Opsiyonel: Dependabot entegrasyonu için bağımlılık grafiğini güncelleyin
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
